UPDATE `events` SET `mode` = 'BULK_REGISTRATION' WHERE `mode` = 'PRE_REGISTERED';
UPDATE `meetings` SET `mode` = 'BULK_REGISTRATION' WHERE `mode` = 'PRE_REGISTERED';

ALTER TABLE `events`
  MODIFY `mode` ENUM('BULK_REGISTRATION', 'PRE_REGISTRATION', 'OPEN_REGISTRATION') NOT NULL;

ALTER TABLE `meetings`
  MODIFY `mode` ENUM('BULK_REGISTRATION', 'PRE_REGISTRATION', 'OPEN_REGISTRATION') NOT NULL DEFAULT 'BULK_REGISTRATION';
